#!/usr/bin/env sh

spacebar -m config position bottom
spacebar -m config title on
spacebar -m config spaces on

spacebar -m config padding_left 16
spacebar -m config padding_right 16

spacebar -m config space_icon 
spacebar -m config spacing_left 17

spacebar -m config text_font "Monaspace Neon:Light:12.0"
spacebar -m config icon_font "Font Awesome 5 Free:Solid:5.0"

spacebar -m config power off
spacebar -m config clock_format "%w %W %d %h %R"
spacebar -m config clock_icon " "
