"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio = [ 2, 5, 4 ]
sort_by = "natural"
sort_dir_first = true
show_hidden = true
linemode = "mtime"

[preview]
max_width = 900
max_height = 1200

