#!/usr/bin/env sh

ctrl + ralt - r : skhd --restart-service

# Space Navigation (four spaces per display)
ralt - 1 : yabai -m space --focus "$(yabai -m query --displays --display | jq '.spaces[0]')"
ralt - 2 : yabai -m space --focus "$(yabai -m query --displays --display | jq '.spaces[1]')"
ralt - 3 : yabai -m space --focus "$(yabai -m query --displays --display | jq '.spaces[2]')"
ralt - 4 : yabai -m space --focus "$(yabai -m query --displays --display | jq '.spaces[3]')"

# Window Navigation (through display borders)
ralt - h    : yabai -m window --focus west  || yabai -m display --focus west
ralt - j    : yabai -m window --focus south || yabai -m display --focus south
ralt - k    : yabai -m window --focus north || yabai -m display --focus north
ralt - l : yabai -m window --focus east  || yabai -m display --focus east

# Float / Unfloat window: lalt - space
ralt - space : yabai -m window --toggle float

# Make window zoom to fullscreen
shift + ralt - f : yabai -m window --toggle zoom-fullscreen

# Make window zoom to parent node
ralt - f : yabai -m window --toggle zoom-parent

############## Aerospace

# fn + ctrl - h : aerospace move left
# fn + ctrl - j : aerospace move down
# fn + ctrl - k : aerospace move up
# fn + ctrl - l : aerospace move right
#
# fn - s : aerospace layout v_accordion
# fn - w : aerospace layout h_accordion
# fn - e : aerospace layout tiles horizontal vertical  # toggle split
# fn - r : aerospace mode resize
#
# fn - f : aerospace fullscreen
# alt - f : aerospace layout floating tiling  # toggle floating window
