#!/usr/bin/env sh

# Reload config
shift + ctrl + fn - r : skhd --restart-service && yabai --restart-service
ctrl + fn - r : skhd --restart-service

# Applications
alt - return : open -na "/Applications/WezTerm.app" ~
alt - w : open -na "Firefox"

# Layouts
alt - i : yabai -m config layout "bsp"
alt - o : yabai -m config layout "stack"
alt - p : yabai -m config layout "float"

# Window Management
fn - f : yabai -m window --toggle float
fn - t : yabai -m window --toggle float

shift + fn - z : yabai -m window --toggle zoom-parent
fn - z : yabai -m window --toggle zoom-fullscreen
ctrl + fn - q : yabai -m window --close

fn - v : yabai -m window --insert south
fn - b : yabai -m window --insert east
fn - s : yabai -m window --toggle split

# Window Movement
fn - h : yabai -m window --focus west
fn - j : yabai -m window --focus south
fn - k : yabai -m window --focus north
fn - l : yabai -m window --focus east

fn - n : yabai -m window --focus stack.next
fn - p : yabai -m window --focus stack.prev

ctrl + fn - h : yabai -m window --stack west
ctrl + fn - j : yabai -m window --stack south
ctrl + fn - k : yabai -m window --stack north
ctrl + fn - l : yabai -m window --stack east

shift + fn - h : yabai -m window --warp west
shift + fn - j : yabai -m window --warp south
shift + fn - k : yabai -m window --warp north
shift + fn - l : yabai -m window --warp east

# Workspaces
shift + fn - 1 : yabai -m window --space 1
shift + fn - 2 : yabai -m window --space 2
shift + fn - 3 : yabai -m window --space 3
shift + fn - 4 : yabai -m window --space 4
shift + fn - 5 : yabai -m window --space 5
shift + fn - 6 : yabai -m window --space 6
shift + fn - 7 : yabai -m window --space 7
shift + fn - 8 : yabai -m window --space 8
shift + fn - 9 : yabai -m window --space 9
