#!/usr/bin/env sh

# Reload config
shift + fn - r : skhd --restart-service && yabai --restart-service

# Applications
alt - return : open -na "/Applications/WezTerm.app" ~
alt - w : open -na "Firefox"

# Layouts
fn - i : yabai -m config layout "bsp"
fn - o : yabai -m config layout "stack"
fn - p : yabai -m config layout "float"
alt - i : yabai -m config layout "bsp"
alt - o : yabai -m config layout "stack"
alt - p : yabai -m config layout "float"

# Window Management
fn - t : yabai -m window --toggle float
fn - e : yabai -m window --toggle split
fn - z : yabai -m window --toggle zoom-parent
fn - f : yabai -m window --toggle zoom-fullscreen
ctrl + fn - q : yabai -m window --close

fn - v : yabai -m window --insert south
fn - b : yabai -m window --insert east
fn - s : yabai -m window --toggle split

# Window Movement
fn - h : yabai -m window --focus west
fn - j : yabai -m window --focus south
fn - k : yabai -m window --focus north
fn - l : yabai -m window --focus east

fn - tab : yabai -m window --focus stack.next
shift + fn - tab : yabai -m window --focus stack.prev

shift + fn - h : yabai -m window --stack west
shift + fn - j : yabai -m window --stack south
shift + fn - k : yabai -m window --stack north
shift + fn - l : yabai -m window --stack east

ctrl + fn - h : yabai -m window --warp west
ctrl + fn - j : yabai -m window --warp south
ctrl + fn - k : yabai -m window --warp north
ctrl + fn - l : yabai -m window --warp east

# Workspaces
ctrl + fn - 1 : yabai -m window --space 1
ctrl + fn - 2 : yabai -m window --space 2
ctrl + fn - 3 : yabai -m window --space 3
ctrl + fn - 4 : yabai -m window --space 4
ctrl + fn - 5 : yabai -m window --space 5
ctrl + fn - 6 : yabai -m window --space 6
ctrl + fn - 7 : yabai -m window --space 7
ctrl + fn - 8 : yabai -m window --space 8
ctrl + fn - 9 : yabai -m window --space 9
