# nudge playback speed
= add speed 0.1
- add speed -0.1

# reset playback speed
+ set speed 1
_ set speed 1

# Seek
# small steps
h seek -5    # left  5 seconds
l seek +5    # right 5 seconds

# medium steps
e seek +10   # forward  10 seconds
E seek -10   # backward 10 seconds

# larger steps
w seek +30   # forward  30 seconds
b seek -30   # backward 30 seconds

# large jumps
j seek -60   # back 1 minute
k seek +60   # forward 1 minute
W seek +300  # forward 5 minutes
B seek -300  # back    5 minutes

# Absolute‐percent
0        seek 0   absolute-percent   # “0” → start
1        seek 10  absolute-percent   # “1” → 10%
2        seek 20  absolute-percent
3        seek 30  absolute-percent
4        seek 40  absolute-percent
5        seek 50  absolute-percent
6        seek 60  absolute-percent
7        seek 70  absolute-percent
8        seek 80  absolute-percent
9        seek 90  absolute-percent
g        seek 0   absolute-percent   # “gg” → start
G        seek 100 absolute-percent   # “G”  → end
^        seek 0   absolute-percent   # “^0” → start
$        seek 100 absolute-percent   # “$” → end
%        seek 50  absolute-percent   # “%”  → middle

