#!/bin/sh

# system services
riverctl spawn "/usr/libexec/xfce-polkit"
riverctl spawn kanshi
riverctl spawn nm-applet
riverctl spawn waybar
riverctl spawn start_wlsunset

# visual
source ~/.config/river/colors.sh
riverctl border-width 3

riverctl default-layout wideriver
~/.nix-profile/bin/wideriver \
    --layout                       left               \
    --layout-alt                   monocle            \
    --stack                        dwindle            \
    --count-master                 1                  \
    --ratio-master                 0.50               \
    --count-wide-left              0                  \
    --ratio-wide                   0.35               \
    --no-smart-gaps                                   \
    --inner-gaps                   6                  \
    --outer-gaps                   6                  \
    --border-width                 3                  \
    --border-width-monocle         0                  \
    --border-width-smart-gaps      0                  \
    --border-color-focused         "$RIVER_FOCUSED"   \
    --border-color-focused-monocle "$RIVER_FOCUSED"   \
    --border-color-unfocused       "$RIVER_UNFOCUSED" \
    --log-threshold                info               \
   > "/tmp/wideriver.${XDG_VTNR}.${USER}.log" 2>&1 &


# keyboard
riverctl set-repeat 30 260

# trackpad
riverctl input "pointer-1452-613-Apple_Inc._Magic_Trackpad" tap enabled
riverctl input "pointer-1452-613-Apple_Inc._Magic_Trackpad" scroll-factor 0.3
riverctl input "pointer-1452-613-Apple_Inc._Magic_Trackpad" pointer-accel 0.11

## cursor behavior
riverctl hide-cursor timeout 10000 # 10 seconds
riverctl hide-cursor when-typing enabled
riverctl set-cursor-warp on-focus-change
riverctl xcursor-theme "Bibata-Modern-Classic" 18

# ensure focus follows cursor behavior
riverctl focus-follows-cursor always

### Keybindings
## window management
# launch terminal and application launcher
riverctl map normal Super Return spawn '~/.local/bin/ghostty'
riverctl map normal Super D spawn "rofi -show drun"

# close windows
riverctl map normal Super+Shift Q close

# focus/swap views
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous
riverctl map normal Super N focus-view next
riverctl map normal Super P focus-view previous
riverctl map normal Super+Shift N swap next
riverctl map normal Super+Shift P swap previous

# move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

## tag management
for i in $(seq 1 9); do
    tag=$((1 << ($i - 1)))
    riverctl map normal Super $i set-focused-tags $tag
    riverctl map normal Super+Shift $i set-view-tags $tag
    riverctl map normal Super+Alt $i toggle-focused-tags $tag
    riverctl map normal Super+Alt+Shift $i toggle-view-tags $tag
done

# focus all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

#scratchpads
term_tag=$((1 << 19))
filemanager_tag=$((1 << 20))
discord_tag=$((1 << 21))

## extra tags
# scratchpads
scratchpad_tag=$((1 << 19))
riverctl map normal Super grave toggle-focused-tags $scratchpad_tag
riverctl map normal Super+Shift grave set-view-tags $scratchpad_tag


## modes
# screenshot
riverctl declare-mode screenshot
riverctl map normal Super S enter-mode screenshot
riverctl map screenshot None Escape enter-mode normal
riverctl map screenshot None F spawn 'grim - | tee ~/Pictures/screenshots/screenshot-$(date +%Y-%m-%d-%H%M%S).png | wl-copy && riverctl enter-mode normal'
riverctl map screenshot None R spawn 'grim -g "$(slurp)" - | tee ~/Pictures/screenshots/screenshot-$(date +%Y-%m-%d-%H%M%S).png | wl-copy && riverctl enter-mode normal'

## layout: wideriver
riverctl map normal Super H send-layout-cmd wideriver "--ratio -0.05"
riverctl map normal Super L send-layout-cmd wideriver "--ratio +0.05"
riverctl map normal Super+Shift H send-layout-cmd wideriver "--count +1"
riverctl map normal Super+Shift L send-layout-cmd wideriver "--count -1"

riverctl map normal Super Escape send-layout-cmd wideriver "--ratio 0.5"
riverctl map normal Super+Shift Escape send-layout-cmd wideriver "--count 1"
riverctl map normal Super+Shift D send-layout-cmd wideriver "--stack diminish"
riverctl map normal Super+Shift W send-layout-cmd wideriver "--stack dwindle"
riverctl map normal Super+Shift E send-layout-cmd wideriver "--stack even"

# orientation
riverctl map normal Super Up send-layout-cmd wideriver "--layout top"
riverctl map normal Super Right send-layout-cmd wideriver "--layout right"
riverctl map normal Super Down send-layout-cmd wideriver "--layout bottom"
riverctl map normal Super Left send-layout-cmd wideriver "--layout left"

# monocle/cycle
riverctl map normal Super M send-layout-cmd wideriver "--layout monocle"
riverctl map normal Super F2 send-layout-cmd wideriver "--layout wide"
riverctl map normal Super W send-layout-cmd wideriver "--layout-toggle"

## fullscreen, float, zoom
riverctl map normal Super Space toggle-float
riverctl map normal Super F toggle-fullscreen
riverctl map normal Super+Shift Return zoom

## mouse
riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

## media/brightness
for mode in normal locked; do
    # volume
    riverctl map $mode None XF86AudioRaiseVolume spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute spawn 'pamixer --toggle-mute'

    # media
    riverctl map $mode None XF86AudioPlay spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext spawn 'playerctl next'

    # brightness
    riverctl map $mode None XF86MonBrightnessUp spawn 'brightnessctl s +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl s 5%-'
done

## floating mode
riverctl declare-mode floating
riverctl map normal Super+Alt F enter-mode floating
riverctl map floating None Escape enter-mode normal

# resize floating windows by 25px
riverctl map -repeat floating None H resize horizontal -25
riverctl map -repeat floating None J resize vertical 25
riverctl map -repeat floating None K resize vertical -25
riverctl map -repeat floating None L resize horizontal 25

# move floating windows by 25px
riverctl map -repeat floating Super H move left 25
riverctl map -repeat floating Super J move down 25
riverctl map -repeat floating Super K move up 25
riverctl map -repeat floating Super L move right 25

# snap floating windows to screen edges
riverctl map floating Super+Shift H snap left
riverctl map floating Super+Shift J snap down
riverctl map floating Super+Shift K snap up
riverctl map floating Super+Shift L snap right

## resize mode
riverctl declare-mode resize
riverctl map normal Super+Alt R enter-mode resize
riverctl map resize None Escape enter-mode normal

# adjust layout main location
riverctl map resize None Up send-layout-cmd rivercarro "main-location top"
riverctl map resize None Right send-layout-cmd rivercarro "main-location right"
riverctl map resize None Down send-layout-cmd rivercarro "main-location bottom"
riverctl map resize None Left send-layout-cmd rivercarro "main-location left"

# adjust layout ratios
riverctl map resize Super H send-layout-cmd rivercarro "main-ratio -0.05"
riverctl map resize Super L send-layout-cmd rivercarro "main-ratio +0.05"

# adjust layout counts
riverctl map resize Super+Shift H send-layout-cmd rivercarro "main-count +1"
riverctl map resize Super+Shift L send-layout-cmd rivercarro "main-count -1"

## rules
# fullscreen rules
riverctl rule-add -app-id "mpv" fullscreen
riverctl rule-add -app-id "org.pwmt.zathura" fullscreen
riverctl rule-add -app-id "feh" fullscreen

# floating rules
riverctl rule-add -app-id "galculator" float
riverctl rule-add -app-id "org.kde.kcalc" float
riverctl rule-add -app-id "thunar" float
riverctl rule-add -app-id "Bitwarden" float
riverctl rule-add -app-id "Vial" float
riverctl rule-add -app-id "blueman-manager" float
riverctl rule-add -app-id "nm-connection-editor" float
riverctl rule-add -app-id "org.pulseaudio.pavucontrol" float
riverctl rule-add -app-id "com.github.wwmm.easyeffects" float
riverctl rule-add -app-id "GParted" float
riverctl rule-add -app-id "nwg-look" float
riverctl rule-add -app-id "firefox" -title 'Picture-in-Picture' float
riverctl rule-add -app-id "zen-alpha" -title 'Picture-in-Picture' float
riverctl rule-add -app-id "io.github.elevenhsoft.WebApps" float
riverctl rule-add -app-id "WebApp-*" float

# server-side decorations
riverctl rule-add ssd
riverctl rule-add -app-id "zen-alpha" ssd
riverctl rule-add -app-id "firefox" ssd
riverctl rule-add -app-id "com.github.wwmm.easyeffects" ssd
riverctl rule-add -app-id "com.mitchellh.ghostty" ssd
riverctl rule-add -app-id "dev.zed.Zed" ssd
riverctl rule-add -app-id "dev.zed.Zed-Dev" ssd
riverctl rule-add -app-id "io.github.elevenhsoft.WebApps" ssd
riverctl rule-add -app-id "WebApp-*" float

## clipboard management
riverctl spawn "wl-paste --type text --watch cliphist store"
riverctl spawn "wl-paste --type image --watch cliphist store"
riverctl map normal Super V spawn "cliphist list | rofi -dmenu -p 'Clipboard' -config $HOME/.config/rofi/regular.rasi | cliphist decode | wl-copy"

# environment initialization
exec dbus-update-activation-environment --all
exec gnome-keyring-daemon --start --components=secrets
exec /usr/libexec/pam_kwallet_init
