separate_workspaces = true
double_click_to_hide = true
center_on_focus = false

[appearance]
icon_size = 64
max_width = 800
min_width = 600
system_theme = "auto"

[appearance.animation.hide]
duration = 100
easing = "ease-out-cubic"

[appearance.animation.resize]
duration = 100
easing = "ease-in-out-cubic"

[appearance.animation.workspace]
duration = 0
transition = "crossfade"

[appearance.animation.switch]
duration = 100
easing = "ease-out-cubic"

[keys]
modifier = "Alt_L"

[keys.window]
close = "x"
abort = "Escape"

[keys.switch]
next = "Tab"
prev = "Shift+Tab"

[keys.workspace]
prev = "Q"
next = "A"
