# ~/.config/alacritty/colors.toml

[colors.primary]
background = "{{background}}"
foreground = "{{foreground}}"

[colors.cursor]
text = "{{color8}}"
cursor = "{{cursor}}"

[colors.selection]
text = "{{foreground}}"
background = "{{color8}}"

[colors.normal]
black = "{{color0}}"
red = "{{color1}}"
green = "{{color2}}"
yellow = "{{color3}}"
blue = "{{color4}}"
magenta = "{{color5}}"
cyan = "{{color6}}"
white = "{{color7}}"

[colors.bright]
black = "{{color8}}"
red = "{{color9}}"
green = "{{color10}}"
yellow = "{{color11}}"
blue = "{{color12}}"
magenta = "{{color13}}"
cyan = "{{color14}}"
white = "{{color15}}"

[colors.search.matches]
foreground = "{{color8}}"
background = "{{color11}}"

[colors.search.focused_match]
foreground = "{{color8}}"
background = "{{color3}}"

[colors.hints.start]
foreground = "{{color8}}"
background = "{{color3}}"

[colors.hints.end]
foreground = "{{color8}}"
background = "{{color1}}"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "{{background}}"
background = "{{foreground}}"

[colors.vi_mode_cursor]
text = "{{color8}}"
cursor = "{{cursor}}"
